### ISSUE TITLE
Slider mouse pointer on drag

### ISSUE THREAD

**Issue by philoliver** [ngx-kit/ngx-kit#186]
Hi,

Firstly, thanks for the framework, its a great approach!!

I generated a ui-slider. Now I face a small problem with the mouse pointer while dragging. In Safari, the mouse pointer changes from "hand" to "select" while dragging the pointer (or being slightly outside of it).

As I understand this can not be changed with css alone.
According to this [post](https://stackoverflow.com/questions/2745028/chrome-sets-cursor-to-text-while-dragging-why), I need to call `event.originalEvent.preventDefault();`.

How do I access the event `event` in ngx-kit?

<img width="584" alt="ui-slider pointer problem" src="https://user-images.githubusercontent.com/6113138/39424089-430db56c-4c75-11e8-941c-4656d0a8f591.png">

**Comment by navix** [comment]
Hello! Thanks for using.

Now in 1.1.2 original mouse-move event is not available outside. But, I've investigated the problem: here you can see `.preventDefault()` call: https://github.com/ngx-kit/ngx-kit/blob/1.1.2/packages/core/src/kit-pointer/kit-pointer-line/kit-pointer-line.directive.ts#L53

> According to this post, I need to call event.originalEvent.preventDefault();.

Notice that `originalEvent` is jQuery specific.

Not sure how exactly it could be fixed.

For the next versions (now 2.0 in an active development), I've switched slider to hammerjs (instead of `KitPointer`), but the problem is still here.

**Comment by navix** [comment]
Not relevant after 2.0 release.
